### ISSUE TITLE
Docker no longer runs any modules

### ISSUE THREAD

**Issue by smped** [bordin89/ICB_docker#2]
I have tried running every module and end up with similar errors every time. The docker worked very well a few months ago, but something has changed which is very surprising given the idea of containers. I have uninstalled & reinstalled multiple times on multiple machines and it's the same everywhere

The errors always contain:

```
Died at /ICB_docker/0_initial_parser.pl line 25.
```

Trying to run TMHMM gives this

```
python /ICB_docker/icb.py -i 5seqs.fasta -tmh


+------------------------------------------------+
|                                                |
|        Integrative Cell Biology Pipeline       |
|                                                |
|             Nicola Bordin, CABD UPO            |
+------------------------------------------------+
Modules available:

PSIBLAST
TMHMM
SignalP
IUPRED
InterProScan
HHPred
HHblits

Execution Parameters
Parsing headers

Died at /ICB_docker/0_initial_parser.pl line 25.
Running TMHMM
Use of uninitialized value $tmhmm_path in concatenation (.) or string at /ICB_docker/run_parse_TMHMM.pl line 37.
sh: TMHMM_raw_results_/tmhmm-2.0c/bin/.tsv: No such file or directory
gzip: TMHMM_raw_results_/tmhmm-2.0c/bin/.tsv: No such file or directory
gzip: TMHMM_raw_results_/tmhmm-2.0c/bin/.tsv.gz: No such file or directory
No such file or directory at /ICB_docker/run_parse_TMHMM.pl line 64.
readline() on closed filehandle IN at /ICB_docker/order_entries.pl line 24.
Use of uninitialized value $header in print at /ICB_docker/order_entries.pl line 38.
gzip: 00_ini*.gz: No such file or directory
Traceback (most recent call last):
  File "/ICB_docker/make_tsv_table.py", line 11, in <module>
    for line in infile:
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

A similar error is seen trying IUPRED

```
python /ICB_docker/icb.py -i 5seqs.fasta -iup


+------------------------------------------------+
|                                                |
|        Integrative Cell Biology Pipeline       |
|                                                |
|             Nicola Bordin, CABD UPO            |
+------------------------------------------------+
Modules available:

PSIBLAST
TMHMM
SignalP
IUPRED
InterProScan
HHPred
HHblits

Execution Parameters
Parsing headers

Died at /ICB_docker/0_initial_parser.pl line 25.
Running IUPred
No such file or directory at /ICB_docker/run_parse_IUPRED.pl line 68.
readline() on closed filehandle IN at /ICB_docker/order_entries.pl line 24.
Use of uninitialized value $header in print at /ICB_docker/order_entries.pl line 38.
gzip: 00_ini*.gz: No such file or directory
Traceback (most recent call last):
  File "/ICB_docker/make_tsv_table.py", line 11, in <module>
    for line in infile:
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

And for the record, the input file is:

```
cat 5seqs.fasta
>YP_001087225.1 diguanylate kinase signaling protein [Clostridioides difficile 630]
MGMENNLRKNNSIMKKMIFPLIIVMLIQTSLFCATILWGGTIKKLNDNSFDILNERVINRKNYIQNEMLQ
RWSNTSETEATINSSVKKVLNEKNALIEDVGNNEEINKDIIKSISNDLIYLLRKNSVTGAFIILSDKNIN
DKSIDSKGEISRTGLYIRDLDPKFNPNDNSDLLIERGSSDIARSFGISMDSYWEPKFSFKSENEQDGDDF
FYKPFRAAIDNPNVSSSNLGYWGSKFLLTNAGDRLMTYTVPLIYEDGTVYGVLGIDLSVNYLRELLPYSE
INGNKKGNYILGVDRNNDMAFENVISNGYSLKEKFWDGLHSNLEQKESYKNIYKIKNKDNECGNGNIYAS
VQYLDLYNSNTPFENERWALLGIIEEKSLLSFSKRVEKLVIISIAISLLIGLIGIYIASRLFTKPIVLLA
NKVRNSNPSKPVNLDKINISEIDELSSAIELLSANVADSSSKLSQIIEMVDMPIGAFELYKNAENVFCTK
EFFSVFTTEIKFEEYGYMEKNKFLKKLRGLDKYLQESYETENTYIYKFESKDKKLKWIRMNIFEDELKVL
GVVVDVTKEFIEKRKIEYERDFDILTNLLNRRAFHSQIQEKFKNKDELKIAAFIMWDLDNLKYINDTYGH
DAGDEYIRCAADILKKFISWNGIVSRLSGDEFYVFIYGYESKDSIRDIINSVKKQMNNTLLKLHDGTEFK
IRASAGISWYPDDSTNYDELMRYADFAMYQIKNTIKGEVSEFDINIYNKDSFLLSNREELNKLIDGQLVE
YAFQPIVDCKGKVFAYEALMRPKIKTFSSPIDVIRLARSQSKLYQIERITWFKALKSFKKYKEKFGDCKL
FLNSIPNNNLSKVDFEEIEDLYGEYLNRVVLEITENDKINEDFIEKKKAYIDHWNIEIALDDFGTGYNGD
AVLLYIMPDYVKIDMSIVRGIDKDENRQKILKNLISYSNERNIKVIAEGVETKGEMETLINLGVDYMQGY
YISKPSFIPEDISDKIKKELKICHENRNDVV
>YP_001088079.1 sporulation-associated two-component sensor histidine kinase [Clostridioides difficile 630]
MDTHNKYVNFIKNIPVPFLYCRIVKRQEDIEYRVEYISKGMGKVLQLEEGICDKNILDVLPVFKSKKYFK
ELFSNEVDCIKRYIPTLKNWINIKKQIIGDSYIILYFGKIVFDYRQIIDSFDKKEKVAYIKDEEGIYIDC
SENLIPILNNNIKTTKDIFGKNDIEVWGENTGKLFRDDYREGVSSKKRFLQNLFEYEETFFMVEKYFLYD
EDELLGTIGIVDNIIYSGYSNRNYNSKDLMKMIEHSIPENMFYKDVYGNYIGFNSGFLNLACMNKEELLG
KNSYKISEEEALIDKIFESDKGVVENKKVVTFELNISMNDENKCIEITKRPFFDSYGSVIGIIGTARDIS
RRKRLEEEMDKTRMEFFANLSHELRTPINLISSSLQVIEKKEADLIESNDTLKRNLGIIKQNGNRILRLV
NNVIDFTKMQSGYLDFKPEESDIIAFIEEICMSVADFASQNNIQLTFDTEIEEFSMLFDSEKLERIILNL
LSNGIKYNKKDGKINIFLYVKDNVFNMKISDSGIGIPKEKIDKIFNRFEQIDNELSYRVKGSGIGLSLVK
SLVELHEGSISLKSQLGIGSEFIVSLPVRSKNNIEKYNHKREISNELSKKLEIEFSDL
>YP_001086912.1 sigma-54 dependent transcriptional regulator [Clostridioides difficile 630]
MNQEIFFKIMNEILENIDEGVHFVNKDGKTIIYNNSVQKMEKMNRHDILTNSFFDIVNKMKINRSTLLEV
LEKREVIKDNIQKYLDKNGKEITAINTTIPIDIKGEFVGALEISKNMTTIENLLNRNYKKNLVNKVSSRQ
KKGYEFDDILGESNLIKEAIAKSKKACKSDASVFIYGETGTGKELFSQSIHYGSNRRNYPFIAQNCAALP
ESLFEGILFGTSKGGFTGAIDRPGLFEQANKGTLLLDEINSMPIMLQAKLLRVLQEGYVRRVGGTKDIPI
DVRIIATTNESPKVILNEHKMRKDLYYRLNIIHIKIPPLRDRKEDIPLLCKKFISKYNKKLNKKVVGISD
EAIKILKNYDWQGNIRELENIIYCTMSMMEDEVQIETSMINLNDYYNLKENKESNNYSLNDLEDKTLSKI
ISEIEEKYIYESLEKASYNITKAASILGMNRQNLQYKIKKYNIKIL
>YP_001089266.1 signaling protein [Clostridioides difficile 630]
MKNVSKKFFVCTIIVLITFLCFSKFAIYVFDKQEKKETKVVENMLNVYKNNIILNLTEKFNYSKDLTSVL
VSNNYSIDKLKPIADEILKNNSCIYISVVEKYNVAAFFSNSVKKDIINTPIQELNYSYSLANSIKGLVVE
GPSKDQFSNGDVFLITNPIYKNGEYWGEITVALDAKKVVDSFNLNKLKESGFEYELWRVHLDNGSKSTIE
ISTKDFNFSKSHEIKFKLPTVWTLSIVYKNGWNNKNIDFIVFVILLIISILIGVMTFIYIEKKSISKELN
QQSLKNLETGILNREGFLIKLQEHLNRKNNEIVLLYICITNYSKFAPVMSFEKRQDYLTHIVKNLDNYIK
SSHFIARISEEGFVLALEENCDKNELLNIEKGISLELLRKIKVENKQVFLTIGYGSSRCVDDRKDAESLL
LSAIEDYERRFPAMSPIHDFTKKCEDMLDEKKQIVFGEYPDLEINKLSKVIYKYYKKVQRIMYKDYNIDI
GNRRGYMRDVEVLIDYNSERMLYLFLIDICKFGKFNELFSIEIGDVILKEVSNKLKTIFSNYLYRINGDV
FLGISIDKESYLDTLHKVNEVFNSSLSVEDVLFDVKCNIGICQYPYHGENPYDLLEKVQIALEYAKKDVK
SNVKVYDKELTEEIYHENNIIKDLKKGLEEQTLEVWYQPIFNVSKNCYIKAEALIRLRNKEGGYYSAYEV
ITYAEKHGLIKDVGLYVLKKACDVTTKIKDKNIDFEQMQLNLSVQQIVHKQCANDILSCIENCGLDKKYI
CVEVTETVLMETFEIVNVTLDKLKKEGISIALDEFGSGFSSINYLANLPIENLKIDKELVEQITYSKKQF
ELLKTIVQIAKINGMDIVAEGVETKETLDLVVTSGVNLIQGHYFSEPLSEDKFIELMIEE
>YP_001089352.1 two-component sensor histidine kinase [Clostridioides difficile 630]
MKIQNTEWGYIEWKHTYDENNPKQAMNIYIAVTMPGKKHFNHVHYGQEQMIYILEGEGLYIINGVWKPFY
QGMIFYIESGSTHETINTGDREIKELIVSNNVDDVGESEIIDINPNNYLKKTLINYSESTLNLYAAVESI
RGQFIDPFKIPLIIYDDSWNIVLKNPYFPLFCFEKCNPMKFPQNCDCMNQKSSNQFVCEYGITIYNIPIL
YKSNSIGVIRGGYVLLSDLNLDTEHNNLYDIPEGAARSIKRLLKQISKNIINFCSFNDIRKDLQEKEKTI
ARTYHYGEQLEMNLKVAQDMVTNLRINHHFLFNTLNSMASIALDDGSYDLYSAIIDLSRMFRYTMRSDLR
FVELESEILYIKNYLNLQKLRYGDALKVKYLIPEKLYNLSVPFNFIQPIVENAFTHGFRDIDTEKRIEII
ARLDSQYAIIEIHNNGTILDGNNIDKIKAGIRSNNGHGLSLIYTKFTSAYGNNFDMDIKSSDNEGTYIMI
KIPIENYKEYV
```

HHPRED runs to completion (I think) and creates output files which are not blank, however it doesn't exit, and simply hangs when it stops updating the output files. After exiting HHPRED inside the container using Ctrl+C the errors were 
```
^C
Interrupt: Killed main process 174
Parsing HHpred output

Error: the script needs 2 parameters

Error: the script needs 2 parameters

Error: the script needs 2 parameters

Error: the script needs 2 parameters

Error: the script needs 2 parameters
readline() on closed filehandle IN at /ICB_docker/order_entries.pl line 24.
Use of uninitialized value $header in print at /ICB_docker/order_entries.pl line 38.
gzip: 00_ini*.gz: No such file or directory
Traceback (most recent call last):
  File "/ICB_docker/make_tsv_table.py", line 11, in <module>
    for line in infile:
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

stdout prior to running the entire HHPRED process also showed the same initial error

```
python /ICB_docker/icb.py -i 5seqs.fasta -hhpred


+------------------------------------------------+
|                                                |
|        Integrative Cell Biology Pipeline       |
|                                                |
|             Nicola Bordin, CABD UPO            |
+------------------------------------------------+
Modules available:

PSIBLAST
TMHMM
SignalP
IUPRED
InterProScan
HHPred
HHblits

Execution Parameters
Parsing headers

Died at /ICB_docker/0_initial_parser.pl line 25.
Running HHpred
Created 5 sequence files
5 files read in ...

```

**Comment by bordin89** [comment]
Hi Steve, I'm sorry you're experiencing this. The package hasn't changed (and I'm no longer mantaining it, I'm afraid, since I moved labs). By the looks of your output, it seems that 

`Died at /ICB_docker/0_initial_parser.pl line 25.` is the issue. 

`Line 25 states scalar (@ARGV) == 2 or die $!;`

In the usage it asks perl <this_script.pl> <input_file> identifier

Could it be that there is an issue with your file name (too short)? 
When I wrote this my Python skills weren't that good to be honest, so I think the issue is with this

`os.system("perl "+os.path.dirname(os.path.realpath(sys.argv[0]))+"/0_initial_parser.pl "+multifasta+" "+multifasta[:-11])`

Can you try with a longer filename and see if the issue remains? 

Thanks!

**Comment by smped** [comment]
Hi @bordin89 ,

Thanks so much for the fast response. I really didn't expect that as I did suspect this was no longer actively supported. I've just run it after renaming the files as you suggested and I actually get output now. There's still an error at the end of the process

```
Error: the script needs 2 parameters
Traceback (most recent call last):
  File "/ICB_docker/make_tsv_table.py", line 11, in <module>
    for line in infile:
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

However, now I can get output this is a real help. Thanks again.
